export const ADD_COMMENT = "ADD_COMMENT";
export const SPINNER_LOADING = "SPINNER_LOADING";
export const MENU_LOADING = "MENU_LOADING";
export const COMMENT_IS_LOADING = "COMMENT_LOADING";
export const COMMENT_LOADED = "COMMENT_LOADED";
export const DISH_LOADFAILED = "LOAD_FAILED";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";
